"""new columns

Revision ID: 02d902f6dcf4
Revises: 
Create Date: 2022-11-27 02:46:08.903178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d902f6dcf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dailyCalorieIntake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weeklyCalorieIntake', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weeklyCalorieIntake')
        batch_op.drop_column('dailyCalorieIntake')

    # ### end Alembic commands ###
